name: msys2

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  stock:
    name: Stock
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ncurses

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make -f Makefile.msys2

  sdl:
    name: SDL2
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make -f Makefile.msys2.sdl2 SOUND=yes

  makefile-win:
    name: Makefile-win
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          # The libraries in src/win/lib and src/win/dll are 32-bit.
          msystem: mingw32
          install: >-
            make
            mingw-w64-i686-gcc

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make -f Makefile.win MINGW=yes

  configure-win:
    runs-on: windows-latest
    defaults:
      # Reduce verbosity and always run with msys2 as the default shell.
      # See https://github.com/marketplace/actions/setup-msys2 .
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          # The libraries in src/win/lib and src/win/dll are 32-bit.
          msystem: mingw32
          install: >-
            autoconf-wrapper
            automake-wrapper
            make
            mingw-w64-i686-gcc

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./autogen.sh
          ./configure --enable-win
          make install
          make tests

asan-ubsan-clang64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up prerequisites
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: CLANG64
          install: >-
            mingw-w64-clang-x86_64-compiler-rt
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-libpng

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build with ASAN/UBSAN
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DCMAKE_C_FLAGS="-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -fno-lto -g" \
            ..
          ninja -j$(nproc) --verbose

      - name: Run Tests with ASAN/UBSAN
        run: |
          cd build
          cmd /c ninja -j$(nproc) alltests