name: Windows

on:
  push:
    branches: [ master, build/remove-autotools-in-favor-of-cmake ]
  pull_request:

jobs:
  build:
    name: Stock 
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 cmake ninja-build

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build with CMake/Ninja
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_C_FLAGS="-Werror" \
            -DSUPPORT_WINDOWS_FRONTEND=ON \
            -DSUPPORT_BUNDLED_PNG=ON \
            -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux-i686-mingw32-cross.cmake \
            ..
          ninja -j$(nproc)
